version: "3.7"
services:
  shopper:
    image: codeboten/shopper:chapter2
    container_name: shopper
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=opentelemetry-collector:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - GROCERY_STORE_URL=http://grocery-store:5000/products
    networks:
      - cloud-native-observability
    depends_on:
      - grocery-store
      - opentelemetry-collector
    stop_grace_period: 1s
  grocery-store:
    image: codeboten/grocery-store:chapter2
    container_name: grocery-store
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4317
      - OTEL_SERVICE_NAME=grocery-store
      - INVENTORY_URL=http://legacy-inventory:5001/inventory
    networks:
      - cloud-native-observability
    depends_on:
      - legacy-inventory
      - opentelemetry-collector
    stop_grace_period: 1s
    ports:
      - 5000:5000
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 80M
  legacy-inventory:
    image: codeboten/legacy-inventory:chapter2
    container_name: inventory
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4317
      - OTEL_SERVICE_NAME=inventory
    networks:
      - cloud-native-observability
    depends_on:
      - opentelemetry-collector
    stop_grace_period: 1s
    ports:
      - 5001:5001
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 80M
  jaeger:
    image: jaegertracing/all-in-one:1.29.0
    container_name: jaeger
    ports:
      - 6831:6831/udp
      - 16686:16686
    networks:
      - cloud-native-observability
  prometheus:
    image: prom/prometheus:v2.29.2
    container_name: prometheus
    volumes:
      - ./config/prometheus/config.yml/:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--enable-feature=exemplar-storage"
    ports:
      - 9090:9090
    networks:
      - cloud-native-observability
  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:0.43.0
    container_name: opentelemetry-collector
    volumes:
      - ./config/collector/config.yml/:/etc/opentelemetry-collector.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--config=/etc/opentelemetry-collector.yml"
    networks:
      - cloud-native-observability
    ports:
      - 4317:4317
      - 13133:13133
      - 8889:8889
    stop_grace_period: 1s
  loki:
    image: grafana/loki:2.3.0
    container_name: loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - cloud-native-observability
  promtail:
    image: grafana/promtail:2.3.0
    container_name: promtail
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - cloud-native-observability
  grafana:
    image: grafana/grafana:8.3.3
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - cloud-native-observability
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ORG_ROLE=Editor
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true

networks:
  cloud-native-observability:
